### ISSUE TITLE
Any plan to support newest version?

### ISSUE THREAD

**Issue by victornoel** [jirutka/jetty-bom#2]
Hi,

This BOM is really useful :) do you plan to support new versions of Jetty?

**Comment by jirutka** [comment]
Hi,

yes, but I'm very busy now. It'd help me a lot if you check whether the list of jetty modules in the BOM POM is still correct (i.e. if there are not some new modules missing in BOM or modules that doesn't exist anymore).

**Comment by victornoel** [comment]
I made a small script to do that :) (I've only covered 9.3.x...)

``` sh
#!/bin/bash
for v in {9.3.7.v20160115,9.3.8.v20160314,9.3.9.v20160517,9.3.10.v20160621,9.3.11.v20160721,9.3.12.v20160915,9.3.13.v20161014}
do
    rm -f $v.txt
    JG=$(curl -s -L "http://search.maven.org/solrsearch/select?q=v:%22$v%22&core=gav&rows=200&wt=xml" | /usr/bin/vendor_perl/xml_grep --nowrap --text_only "result/doc/str[@name = 'g']" | sort -u | grep '^org\.eclipse\.jetty')
    for g in $JG
    do
        curl -s -L "http://search.maven.org/solrsearch/select?q=g:%22$g%22+AND+v:%22$v%22&core=gav&rows=200&wt=xml" \
            | /usr/bin/vendor_perl/xml_grep --nowrap --text_only "result/doc/str[@name = 'a']" \
            | sed "s/^/$g:/" >> $v.txt
    done
    sort -o $v.txt $v.txt
    if [ -n "$PREV" ]
    then
        echo "Diff between $PREV and $v:"
        diff -u $PREV.txt $v.txt
    fi
    PREV=$v
done
```

I checked by hand the difference between jetty-bom and the generated file for `9.3.7.v20160115`:
- Yours is missing:
  - `org.eclipse.jetty.gcloud:jetty-gcloud-session-manager`
  - `org.eclipse.jetty:apache-jsp`
  - `org.eclipse.jetty:apache-jstl`
- It's also missing the osgi artefacts, not sure if it is on purpose, but I think it could make sense to have them...
- Maybe `org.eclipse.jetty:jetty-jspc-maven-plugin` and `org.eclipse.jetty:jetty-maven-plugin` should be in `pluginsManagement` instead?

And in terms of changes after that:
- `org.eclipse.jetty:jetty-documentation` was added with 9.3.9 onward
- `org.eclipse.jetty.gcloud:jetty-gcloud-memcached-session-manager` was added with 9.3.11 onward
- nothing was removed

I understand now it is very heavy to maintain such a bom... :)

**Comment by jirutka** [comment]
Thanks a lot for help! I’ve added missing artifacts and uploaded 9.3.14.v20161028 and 9.2.19.v20160908 to Maven Central.

> Maybe `org.eclipse.jetty:jetty-jspc-maven-plugin` and `org.eclipse.jetty:jetty-maven-plugin` should be in `pluginsManagement` instead?

I’m not sure if `pluginsManagement` is correctly inherited in the same way as `dependencyManagement`, so I kept it in `dependencyManagement` for now.

**Comment by victornoel** [comment]
It would be great to have also the intermediate versions for people that need them :)

I think you are right for pluginManagement: it is not inherited from an import scope, I checked!
